### ISSUE TITLE
Ctrl+H replace support would be nice

### ISSUE THREAD

**Issue by mitranim** [GoogleChromeLabs/text-app#129]
Ctrl+H auto-replace is likely the biggest advantage of desktop editors over web-based ones, nearly all of which lack this feature. Text-app is a desktop editor that currently lacks this feature. Adding it would be very nice and bring it up to speed.

**Comment by ktrachy** [comment]
I like your simple design with this editor but I have to agree about a search and replace.  This is a very important function that is a must for anyone.  Please consider adding this as soon as possible.  

If someone is enters a string in the find/search box why not simple show another box for replace.  It is intuitive.  Definitely tie it to the search.  I looked and looked around the UI and that was the first place I looked.  I guess you could call the original box Search/Replace.  Someone enters something in the Search/Replace field and it spawns a Replace field.

Please elevate the importance of adding this feature.  I actually had to open google docs for this feature.  Sorry.
