### ISSUE TITLE
Tab Indentation are made of spaces instead of tabs, when CR to a new line

### ISSUE THREAD

**Issue by jacobopantoja** [GoogleChromeLabs/text-app#200]
At least in 0.4.90 in Samsung ARM Chromebook, even if you have "Tab to spaces" disabled, when you have the current line indented with a Tab and then hit <return> the new line keeps the indentation, but the indentation is built upon spaces instead of tab.

IMHO this is a bug because the behaviour is not consistent.

**Comment by BugsNash** [comment]
Fixed with #269.
