### ISSUE TITLE
Add keyboard shortcuts.

### ISSUE THREAD

**Issue by eterevsky** [GoogleChromeLabs/text-app#21]
- CTRL+TAB = rotate through open docs
- CTRL+N = new file
- CTRL+O = open dialog
- CTRL+S = save
- CTRL+SHIFT+S = save as
- CTRL+F = open search
- CTRL+Z = undo
- CTRL+Y = redo
- CTRL+C = copy
- CTRL+X = cut
- CTRL+V = paste
- CTRL+A = select all
- CTRL+space = open/ close sidebar
- CTRL++ = increase font size
- CTRL+- = decrease font size

**Comment by wilsmi** [comment]
CTRL+space does not open/close the sidebar...

**Comment by beaufortfrancois** [comment]
Actually <Alt>+<Space> toggles the slidebar.
See https://github.com/GoogleChrome/text-app/blob/7783e6ee6b6a07c9e2fd36d4adc03478bfdfa4c7/js/controllers/hotkeys.js#L109-L114
