### ISSUE TITLE
Warning when closing unsaved document

### ISSUE THREAD

**Issue by mrFbn** [GoogleChromeLabs/text-app#224]
When closing a document that is changed not saved yet there should be a warning or a question if user want's to save.

Right now if I accidentially click on close all my work is lost if it was not saved.

**Comment by victorel-petrovich** [comment]
@eterevsky 
Then how come Caret does exactly this thing that you are saying ChromeOS doesn't allow? 
https://chrome.google.com/webstore/detail/caret/fljalecfjciodhpcledpamjachpmelml
