### ISSUE TITLE
Fix: Cannot read property 'getSession' of null at Tabs.onDocChanged_

### ISSUE THREAD

**Issue by eterevsky** [GoogleChromeLabs/text-app#229]
TypeError: Cannot read property 'getSession' of null at Tabs.onDocChanged_ (chrome-extension://mmfbcljfglbokpmkimbfghdkjmjhdgbg/js/all.js:558:86) at HTMLDocument.v.event.dispatch (chrome-extension://mmfbcljfglbokpmkimbfghdkjmjhdgbg/lib/jquery-1.8.3.min.js:2:38053) at HTMLDocument.o.handle.u (chrome-extension://mmfbcljfglbokpmkimbfghdkjmjhdgbg/lib/jquery-1.8.3.min.js:2:33923) at Object.v.event.trigger (chrome-extension://mmfbcljfglbokpmkimbfghdkjmjhdgbg/lib/jquery-1.8.3.min.js:2:3

**Comment by BugsNash** [comment]
Can't repro
