### ISSUE TITLE
TEXT downloading problem

### ISSUE THREAD

**Issue by BakedPuma** [GoogleChromeLabs/text-app#256]
so, i am trying to get text. im on a chromebook, so i have no clue what im doing. but, i hit the button to get it. it says its already downloaded, but i cant even open it or find it. i go through my apps and it isnt in there

**Comment by BugsNash** [comment]
Hi BakedPuma, you should be able to open the Text app like any other app on a chromebook using the app launcher.

Closing as this is not an issue in the Text app.
