### ISSUE TITLE
I can't view how my HTML looks on my browser

### ISSUE THREAD

**Issue by HunterEelman** [GoogleChromeLabs/text-app#257]
I can't view how my HTML looks on my browser. I spent a lot of time on typing the HTML codes and all I even bought a book on HTML and CSS and now I can't even view how my works looks on the World Wide Web/ I'm sad :-1:

**Comment by BugsNash** [comment]
If you're working on a chromebook you can do this from the files app, right click on your html file, click open with..., click view, and your html file will open in the browser.

Closing as this isn't an issue in the Text app

**Comment by HunterEelman** [comment]
this was three years ago it isn't an issue anymore
