### ISSUE TITLE
close-window (ctrl-w) sometimes closes entire app not just current file

### ISSUE THREAD

**Issue by addn** [GoogleChromeLabs/text-app#279]
2015.9.8 update:
. since buying a new chromebook I haven't had this problem;
I'm wondering if malware can modify chromebook apps,
and then verified boot doesn't check app integrity.
2015.7.29:
. doing a close-window (ctrl-w) sometimes closes the entire app not just current file;
when it does mistakenly close the entire app,
it will close all remaining files without saving them,
so then some work is lost.
. sometimes ctrl-w is working correctly, 
so reproducing the problem could take several examples;
it may depend upon where in the list of files you are closing,
or in what order the list was formed.

**Comment by BugsNash** [comment]
Hi addn

I can't repro this issue. Are you able to provide steps to reliably reproduce?

**Comment by addn** [comment]
sorry I didn't close this issue to match my update saying not a problem on new chromebook.
