### ISSUE TITLE
it shows the wrong content when opened from files.app on chromeos

### ISSUE THREAD

**Issue by mitoshima** [GoogleChromeLabs/text-app#283]
I couldn't really find the exact pattern, but here is the typical steps I encounter the issue.

1) Open files app on ChromeOS
2) double click text file a. It starts Text app, and opens the content
3) close the text window
4) double click another text file b. It starts Text app, the file b is listed on the left side, but the file a) is still selected and a's content is shown.

I believe in 4), it should show the content of b, shouldn't it?

**Comment by Cobiskuit** [comment]
This behavior persists when opening anything in Text, I've noticed. I just tried it with an html file I was editing.

**Comment by BugsNash** [comment]
I am not able to repro following the steps you provided. Are you able to provide steps that reliably reproduce the problem?

**Comment by BugsNash** [comment]
Closing as can't repro
