### ISSUE TITLE
Can I use these files on other operating systems?

### ISSUE THREAD

**Issue by Adamarin** [GoogleChromeLabs/text-app#286]
Thanks for an alternative program to Google's memo pad. I enjoy this program for large note taking and the ability to move saved files around. The description says this program is made for Google OS but I have to ask, is it possible to save these plain text files and use them on other operating systems without much hassle? Can I save a file in this program, put it on a hard drive, and open it up on Windows or Mac?

**Comment by Cobiskuit** [comment]
Since the files are (by default) .txt files, yes. You should be able to move them to any operating system (Windows, Mac, Linux, etc.) without much hassle, assuming you have a program on the operating system that can read .txt files. Most of the modern operating systems do by default.
