### ISSUE TITLE
Failing to open files

### ISSUE THREAD

**Issue by tarcey** [GoogleChromeLabs/text-app#287]
Sometimes the app fails to open a file.
I use Xfce with Xfwm and the Thunar file manager in Arch Linux, opening a file through the right-click menu sometimes results in the problem.
'Text' loads but does not open a file, the title says "ERROR". Issues like this are unique to 'Text' so i assume that my DE and File Manager are unrelated to this problem, but i might be wrong.
Retrying does not help, only waiting for a random amount of time.

Sometimes 'Text' opens the wrong file, which is usually a previously opened file. Even if i close all tabs in 'Text' before opening the file.

**Comment by BugsNash** [comment]
Closing as can't repro.
