### ISSUE TITLE
Auto-save backup files

### ISSUE THREAD

**Issue by johnstultz-work** [GoogleChromeLabs/text-app#290]
It would be very nice if it auto-saved backup files for any unsaved files. I find myself losing data quite often when I reset to upgrade or shut the machine down, or otherwise accidentally close the window without saving.

**Comment by tamboril** [comment]
Yep.  I really like the app.  First thing I noticed is lack of recovery.
The app needs to "just work" if Chrome is closed, if the window is closed, or if the machine is rebooted.

**Comment by BugsNash** [comment]
Part of this issue (closing window without saving) was fixed in #336. Auto saving when machine is shut down or otherwise force quit remains an issue.

**Comment by BugsNash** [comment]
Duplicate of #20
