### ISSUE TITLE
running python script

### ISSUE THREAD

**Issue by ashok-arora** [GoogleChromeLabs/text-app#294]
after writing and saving it as .py file, how do you run it ?

**Comment by BugsNash** [comment]
Closing the issue as this is outside of the scope of the Text app (which is only for editing files, not running them). 

How to run python scripts depends on your operating system. For chromeos one way you can access a shell is by activating developer mode (details [here](https://www.chromium.org/chromium-os/poking-around-your-chrome-os-device)). There are also chrome apps (from the chrome web store) and android apps (from the play store) that you can use to get a shell on chromebook.
