### ISSUE TITLE
Forward Delete

### ISSUE THREAD

**Issue by latashadoylewrites** [GoogleChromeLabs/text-app#295]
Question: I will be typing along and suddenly the <text> app on my Chromebook is forward deleting. I have a Windows USB keyboard, and I'm 99% sure I'm hitting Shift+Backspace but I don't know what the third key is. I also have no clue how to undo this. Does anyone know the shortcut for forward delete in this app?

**Comment by BugsNash** [comment]
You might have hit the 'Insert' key

**Comment by BugsNash** [comment]
Closing this as a dup of #347

**Comment by BugsNash** [comment]
Actually #347 is a dup of this, whoops
