### ISSUE TITLE
Search & Replace text

### ISSUE THREAD

**Issue by locvfx** [GoogleChromeLabs/text-app#297]
Yes, there is a search input but we really need a **Search&Replace** !
Btw, the app is well designed. I really love it.

**Comment by smdvmx** [comment]
search and replace is critical. We often search for a large bloc of text/code and replace it with another large block of text/code with the modifications needed. It's much simpler and faster than some ridiculous CMS. So please yes include that.

**Comment by henrywright** [comment]
#285

**Comment by BugsNash** [comment]
Duplicate of #121
