### ISSUE TITLE
freezing often may be related to chrome os update or new malware

### ISSUE THREAD

**Issue by addn** [GoogleChromeLabs/text-app#302]
. text.app has been a solid performer for a very long time;
but in the past week it has froze 3 times in 2 days.
. when it freezes it blocks the screen capture
unless it is not getting the focus
(some other app has to be in the foreground).

**Comment by synthstow** [comment]
It happens to mine after about 5 minutes -- I have about 600lines I'm checking and by the time I make it halfway down the page it crashes.
seems worse using the search function maybe?

**Comment by synthstow** [comment]
eugh and I have to power off / on in order to open the program again

**Comment by addn** [comment]
I use it only for briefly previewing and searching files and it has been fine.
I used to use chrome browser for that but this app made itself the default viewer.

**Comment by BugsNash** [comment]
Thanks addn. Closing this issue as it seems to have resolved. Please reopen if it continues to be a problem.
