### ISSUE TITLE
Cursor does not align with text

### ISSUE THREAD

**Issue by massivecreature** [GoogleChromeLabs/text-app#304]
My cursor in the app does not align with text. I've tried changing the font size and the zoom, but to no avail. How can I fix this, please? Thank you.

Edit: Turning off Tabs to Spaces, Smart Indent, and Line Numbers seems to have fixed it.

**Comment by BugsNash** [comment]
I can't repro this. Are you still seeing this when you have Tabs to Spaces, Smart Indent, and Line Numbers all turned on?

**Comment by BugsNash** [comment]
Closing as this seem to be handled in #356
