### ISSUE TITLE
fix "Chrome OS" naming in Github description

### ISSUE THREAD

**Issue by vapier** [GoogleChromeLabs/text-app#309]
can't send a PR for this ;)

the text when you visit this page:
  https://github.com/GoogleChrome/text-app

`A text editor for ChromeOS and Chrome https://chrome.google.com/webstore/de…`

that should read "Chrome OS" instead

**Comment by SHADOWELITE7** [comment]
It doesn't just run on the chrome operating system
It can also run on
Windows 
Mac
Linux

**Comment by vapier** [comment]
that is no longer the case.  Chrome Apps are being disabled for Windows/macOS/Linux.

**Comment by SHADOWELITE7** [comment]
what apps that can only be used on chromeos

**Comment by vapier** [comment]
all apps.  please see:
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by BugsNash** [comment]
Fixed in #308
