### ISSUE TITLE
Changes made with another text editor are not shown

### ISSUE THREAD

**Issue by r2453** [GoogleChromeLabs/text-app#311]
I edited a file in the Text app, then edited it again in notepad.  When I opened it with the Text app again the changes did not appear.  I opened the file in Google Chrome, and the changes were there.

**Comment by SHADOWELITE7** [comment]
you may have made the `Text app` as your default text editor

**Comment by BugsNash** [comment]
Hi r2453. Are you closing the file in the text app in between the 2 edits?

**Comment by r2453** [comment]
I am not sure what the problem was, but I have never had it again.
