### ISSUE TITLE
Song Coding

### ISSUE THREAD

**Issue by LunaBear0323** [GoogleChromeLabs/text-app#313]
![screenshot 2017-11-16 at 9 46 01 am](https://user-images.githubusercontent.com/29279908/32906837-0ba99e18-cab3-11e7-8c3a-d5f3ac47c0f5.png)
![screenshot 2017-11-16 at 9 45 51 am](https://user-images.githubusercontent.com/29279908/32906839-0bcd8756-cab3-11e7-9cbe-ff4ba85eecd5.png)
I am having trouble with coding a song lyric. I am working on creating lyrics & uploading them to my sister's MP3 because it has a lyric function. "Yesterday Once More" was a pre-installed song, so it already has everything, but "Mary, Did You Know" I created has complete lyrics, but there are some things I don't recognize. For example, "[sign:]" or "[count:]" I don't know about. As for the pre-installed song, it had a number for "[count:]" & I have no idea what it was. I thought it was the numbers of characters in the whole text, but when I copy-pasted it on a character count site, it didn't match up. Can someone help and also tell me the meaning of "[sign:] [count:] [offset:] & [ar:] for me please? (when translating the Chinese characters from the ar section, they explain the kind of song it is)

**Comment by LunaBear0323** [comment]
Nvm, I found what I needed. Originally it was an LRC file so I looked it up and found it on Wikipideia

**Comment by orozco22** [comment]
Weak

On Nov 16, 2017 12:48 PM, "LunaBear0323" <notifications@github.com> wrote:
Nvm, I found what I needed. Originally it was an LRC file so I looked it up and found it on Wikipideia
