### ISSUE TITLE
Sidebar menu is broken

### ISSUE THREAD

**Issue by MarsGoodmine** [GoogleChromeLabs/text-app#323]
When I open the sidebar menu, it doesn't function properly, settings don't save and I can't close the menu.

**Comment by BugsNash** [comment]
Hi MarsGoodmine. I can't reproduce this issue, can you tell me what OS and version of chrome you're using?

**Comment by MarsGoodmine** [comment]
I don't know what happened, but the issue resolved itself. I updated chrome and the app functioned perfectly from that point on.
