### ISSUE TITLE
Font ligatures causing misalignment

### ISSUE THREAD

**Issue by randName** [GoogleChromeLabs/text-app#356]
Found #304 but the proposed fix does not work. Realised that it is the "fl" and "fi" ligatures.

![font_bug](https://user-images.githubusercontent.com/123800/41882958-768e7aea-791e-11e8-8c2d-3e3e1b052905.png)

**Comment by BugsNash** [comment]
Thanks for following up on this! Can you please clarify where the misalignment on your screenshot is occurring? if I open the text app with the text pictured here the alignment seems to be fine

**Comment by randName** [comment]
in the picture above it's where "sdflasd" and "jlfidk" are, but I think I should show with a larger font and more lines:
![screenshot 2018-06-27 at 12 22 06](https://user-images.githubusercontent.com/123800/41952911-1b226792-7a05-11e8-8b09-dd10bd949357.png)
In the image above, the cursor is actually at the end of the line (there is no space)
![screenshot 2018-06-27 at 12 22 17](https://user-images.githubusercontent.com/123800/41952912-1b795750-7a05-11e8-9592-14b124798f4f.png)
And I just found this, but if I highlight one of the characters affected, the alignment goes back. In this case the "d" is highlighted but the actual character is the "l" before it (due to the "fi" earlier in the line)
![screenshot 2018-06-27 at 12 22 24](https://user-images.githubusercontent.com/123800/41952913-1bdc1eee-7a05-11e8-81b2-47951accfaea.png)
The alignment goes back for the whole document apparently.
![screenshot 2018-06-27 at 12 22 46](https://user-images.githubusercontent.com/123800/41952914-1c0c9d80-7a05-11e8-9b76-c8fc9bf0c627.png)

**Comment by BugsNash** [comment]
Thanks for clarifying. I can't repro this, using these ligatures doesn't mess up the alignment for me. Can you please tell me what OS, chrome version, and text app version you are using? Also how are you inputting the ligatures? Through a keyboard shortcut?

**Comment by randName** [comment]
Chrome OS Version 67.0.3396.87 (Official Build) (64-bit)
Text App version: 0.5.87

The ligatures automatically appear when I type the 2 characters side by side. No key combination required. Could be a more general font issue in Chrome OS, but I don't see it in other apps.

**Comment by GitBoudewijn** [comment]
I don't have this issue either. Did you maybe change the default fonts in **chrome://settings/fonts**?

**Comment by randName** [comment]
Yes, I'm using the Noto fonts from Google (which isn't the font I use for Secure Shell).
I found this googlei18n/noto-fonts#1021 which seems to be the main issue.

Thanks!

**Comment by BugsNash** [comment]
Good work GitBoudewijn and randName! Closing this.
