### ISSUE TITLE
can no longer open

### ISSUE THREAD

**Issue by hywu0110** [GoogleChromeLabs/text-app#382]
The app can no longer open on my Pixelbook. Tried reboot but did not help. Any more detailed information needed for this issue? I'm using Text app version 0.5.96, and ChromeOS version 69.0.3497.95.

**Comment by BugsNash** [comment]
Hi hywu0110

I can't reproduce this on a Pixelbook using the same Text app version. I am installing the same Chrome version now and will check that soon.

When you say it can no longer open, do you mean that when you try to open it nothing happens? Or do you see some error message?

Have you tried uninstalling and reinstalling the text app? You can do this by going to chrome://extensions, finding the Text app and clicking 'Remove' (but please check if there are any errors listed on the app, if so you might see an 'Errors' button to check them). You can reinstall the Text app from the [Chrome web store page](https://chrome.google.com/webstore/detail/text/mmfbcljfglbokpmkimbfghdkjmjhdgbg)

**Comment by BugsNash** [comment]
Have confirmed that this does not repro for me with Chrome version 69.0.3497.95 and Text app version 0.5.96 on a Pixelbook.

**Comment by hywu0110** [comment]
It fixed itself. I'll close this issue.

**Comment by BugsNash** [comment]
Thanks hywu0110 :)
