### ISSUE TITLE
Set the UI font to roboto

### ISSUE THREAD

**Issue by nmcain** [GoogleChromeLabs/text-app#445]
If text is going to look better on chrome os we should probably substitue the current font for roboto.

**Comment by nmcain** [comment]
UI font

**Comment by BugsNash** [comment]
Looks like the UI refresh mocks call for Google sans font in the menus.

UI refresh overall issue is #345

**Comment by nmcain** [comment]
Is that legal? I can apply it if you want.

**Comment by BugsNash** [comment]
Looks like it's possible but not as an external contributor unfortunately :(

**Comment by nmcain** [comment]
Why not? I have the font files that I extracted from Google fonts, and
could just link them in as an external source and then just cache them on
the user's device using a service worker.

**Comment by BugsNash** [comment]
Google sans doesn't have an open source licence (see [here](https://fonts.google.com/license/productsans)), so I don't think that would be allowed. The font has been used in the past on a Google open source project by depending on a package from a private github repo. 

If you would like to talk to someone who knows more about it than me, I would suggest contacting mux-fonts@google.com

**Comment by nmcain** [comment]
But having it located online and sourcing it via the google fonts link ,
then being cached to a a part of the user's device that is not accessible
unless they are in developer mode, that techincally does not put the font
in the repo, thus keeping the font secure, would that be good?

**Comment by BugsNash** [comment]
I'm not sure if that would be legal, but we would prefer not to access any assets online. The app should be able to be lauched for the first time offline.
