### ISSUE TITLE
Save and Save as do not work

### ISSUE THREAD

**Issue by TheBilgeRat** [GoogleChromeLabs/text-app#448]
Frequency:  Always
Running on Google Pixelbook.  Text launches fine, am able to edit, but save or save as buttons do nothing.  Neither does ctrl-s.  This makes the program useless for its intended purpose.

**Comment by BugsNash** [comment]
Hi TheBilgeRat

I am not able to repro this on a pixelbook with stable version 0.5.96 nor canary version 0.5.154.

Can you try uninstalling then reinstalling the app?

**Comment by BugsNash** [comment]
Closing as can't repro and no feedback from OP. Please reopen if this is still an issue.
