### ISSUE TITLE
Red dots replaced text characters

### ISSUE THREAD

**Issue by Ukieman** [GoogleChromeLabs/text-app#468]
Created a note, closed it, went to reopen file but all text was replaced with rows of red dots. Using Acer Chromebook R13, browser on latest version, txt app setting are same as always. Only thing that I could think is different with this file is that I also saved it to Google Drive but don't recall if I tried to open it in Google Drive or tried to open file using File Manager in Chromebook, Downloads, File. Tried to duplicate this bug by creating a test note in txt app, saving copy to Google Drive, etc. etc. but could not replicate problem.  It's only started happening around time of last Chrome update and only two files have had this problem so far.
![Screenshot 2019-06-06 at 11 32 31 AM](https://user-images.githubusercontent.com/17802033/59059298-76e6a180-8853-11e9-924e-7a71be620f60.png)

**Comment by BugsNash** [comment]
Well that's a strange one!

Thanks for filing. Can you please share one of the files you are seeing this with?

**Comment by Ukieman** [comment]
I included screenshot of file in my last post, It shows settings on left side and what the file looks like when opened.  But I will attach the actual file as well in this response.
[teamviewer sound.txt](https://github.com/GoogleChromeLabs/text-app/files/3263823/teamviewer.sound.txt)

**Comment by BugsNash** [comment]
Ah ok it seems like the file has become corrupted somehow. Those red dots must be how the text app renders unknown characters. If you open the file in Chrome or Safari it shows question mark characters, if you open in in TextEdit or Notes on Mac it shows an empty file, sublime opens it in hexadecimal with just '0' characters.

Did you create the file in the Text app? Did it always have a .txt extension? Do you remember what the original content was?

**Comment by Ukieman** [comment]
YES, extensions have always been same *.txt Yes created in the 'txt' Chrome
extension app.   As for content of the two files, one called Teaview
Sound.txt and other Install APK from PC with ADB.txt.  Both were brief note
on subject matter described in the title of each file.  As you said
probably corrupted somehow just odd that after two years using this
app/extension  had two files like this.  If it happens again I will just
find another app to use as we all know these little programs/extensions
rarely get fixed, assuming it has bug and not something I did but can't
remember what nor was I able to reproduce the problem. Thanks for
responding.

**Comment by BugsNash** [comment]
Thanks for the extra info. It seems like there are several different applications touching the files - Text app, ChromeOS file system, ChromeOS Files app, Google Drive, maybe even a third party txt editor in Google Drive. It's difficult to figure out whether it is the Text app that has caused this file corruption, and without being able to reproduce there isn't much we can do. Please let us know if you see this again/can find a way to reproduce.

**Comment by zardoz01** [comment]
Same thing for me. Red dots over my txt doc. This corruption is an unacceptable aspect of using the Chrome OS. After using Windows for decades I never had a txt doc become corrupted for no reason. I've only been using Chrome OS for 3 or 4 years but this has never happened before. I've lost hours of work and I'm not happy. Exactly the same issue as Ukieman. I'll see if I can open the file as a binary & try to figure out if I can recover anything. Big black mark here guys :-(.

**Comment by whatisreb00t** [comment]
@zardoz01 you are absolutely right!! This is totally an unacceptable aspect. This just happened to me. Like w t f ?

**Comment by TCoding-ProtonExp** [comment]
Same problem here. I lost my entire essay 😿
