### ISSUE TITLE
G Suite Spell Check enabled but still not working

### ISSUE THREAD

**Issue by francesco1119** [GoogleChromeLabs/text-app#469]
Hello, 

I've enabled the spell check from the G Suite console allowing the user to decide if using the Spell Check or not:

![Enabled](https://user-images.githubusercontent.com/3397477/59677526-58c15f80-91ca-11e9-956f-95f3f2ade7f7.png)

I then enabled it on my Chrome: 

![Enabled on mine](https://user-images.githubusercontent.com/3397477/59677531-5e1eaa00-91ca-11e9-9fa2-7e43a5880104.png)

But it still won't correct the errors: 

![Still wont work](https://user-images.githubusercontent.com/3397477/59677576-768ec480-91ca-11e9-9857-83436058f54b.png)

Am I doing anything wrong?

**Comment by BugsNash** [comment]
Hi francesco1119

This is for filing bugs and feature requests on the Text app. It looks like you require tech support for a problem in GSuite that is unrelated to the Text app. 

Gsuite tech support can be found at https://gsuite.google.com/support/

Closing issue as it doesn't seem to be related to the Text app. Feel free to open another issue if there is a problem in the Text app.
