### ISSUE TITLE
had to hard reset chromebook hardware; all text files gone

### ISSUE THREAD

**Issue by wizardlizard12** [GoogleChromeLabs/text-app#470]
hi a little while ago my mouse was being wonky so i did a hard reset and it fixed it. i knew i might lose my downloads, but all of my (many) saved text files are gone too :( is there any way i can get them back? i had so many notes that i really need

**Comment by DavidPeterWlms** [comment]
This might help. Something similar happened to me. By searching for the
name one of the Txt filenames that I remembered, I was then able to
rediscover the folder where I had setup all of the Text-app files to be
kept and...BINGO.
Hope this helps

**Comment by BugsNash** [comment]
I suppose it depends where you were saving the files. I imagine that a factory reset of a chromebook would wipe all local files. If they are stored in Google Drive then they should still be accessible after a factory reset. 

DavidPeterWlms were you storing your text files locally?

Closing the issue as there doesn't seem to be a problem in the Text app.
