### ISSUE TITLE
Turning off smart indent doesn't work

### ISSUE THREAD

**Issue by GitBoudewijn** [GoogleChromeLabs/text-app#471]
If you turn off smart indent and for example do the following:
```
<html>
    <body>ꕯ
</html>
```
And then hit enter you will end up with this:
```
<html>
    <body>
    ꕯ
</html>
```

**Comment by BugsNash** [comment]
This is working as intended.

What you seem to be referring to is the ability to turn off automatic indentation to match the current level of indentation. This is not a feature that can be turned off currently.

Smart indent is automatic indentation based on the syntax of the language you are currently writing in (based on file extension). E.g. in html this means automatically indenting an extra space on the line after a open tag. So in your example with smart indent on you should see this

`<html>
    <body>
        I
`

And with smart indent off you should see this 

`<html>
    <body>
    I
`

If you would like the ability to turn off automatic indentation to match the current level feel free to open another issue.
