### ISSUE TITLE
Chromebook txt application

### ISSUE THREAD

**Issue by Joshgam** [GoogleChromeLabs/text-app#501]
Im trying to notify google of a link to disavow for a website. It says the domain must be uploaded as a text file encoded in either UTF-8 or 7-bit Ascii. Does anyone know if this is how the google txt application encodes text files?

**Comment by BugsNash** [comment]
Hi Joshgam

The text app writes files using FileWriter.write, which I believe uses a UTF-8 encoding. Spec is here https://dev.w3.org/2009/dap/file-system/file-writer.html
