### ISSUE TITLE
Text editor window dimensions can no longer be adjusted

### ISSUE THREAD

**Issue by samh001** [GoogleChromeLabs/text-app#504]
Using Chrome OS (updated to 81.0.4044.127) and Text version 0.5.168.  It is no longer possible to grab the edge of the text editor window to perform window resizing.

[UPDATE]  My problem was fixed by simply uninstalling and re-installing the Text app.
Thanks for the suggestion!

**Comment by zainafzal08** [comment]
Hey samh001! Thanks for filing the bug, i can't seem to reproduce this issue with my version of the app (same version on the same major release of chromeos), can i ask what device you are using and if you are using a mouse or touch screen?

**Comment by BugsNash** [comment]
I also can't repro this on Chrome OS (updated to 81.0.4044.127) and Text version 0.5.168.

samh001 have you tried restarting, and uninstalling/reinstalling the text app?

**Comment by samh001** [comment]
I uninstalled and reinstalled the Text app, and that did indeed fix the problem!  Now using the touchpad cursor it is easy to grab any edge of the Text window to resize.  Before that, I could only grab the edge in the upper left corner of the window. Thanks for the suggestion!Sam
---------- Original Message ----------

**Comment by samh001** [comment]
I took a suggestion to uninstall and re-install the Text app, and that fixed the problem!  Now using the touchpad cursor it is easy to grab any edge of the Text window to resize.  Before that, I could only grab the edge in the upper left corner of the window. I will add commentary to the case report. Thanks,Sam

---------- Original Message ----------

**Comment by samh001** [comment]
Problem was fixed by removing and reinstalling the Text app.
