### ISSUE TITLE
color coding isnt working

### ISSUE THREAD

**Issue by 50izac02** [GoogleChromeLabs/text-app#511]
<h> i tried everything but for some reason it is not clor coding my tags or nothing it annoys me how people comment "oh i lost a story i was writing" and stuff but this is a real issue it aggravates me so much if you guys could figure out why that would be nice i really need that to know whats what </h>
![image](https://user-images.githubusercontent.com/54924164/84061259-9b57eb00-a98b-11ea-9f60-6089301df46c.png)

thx

**Comment by zainafzal08** [comment]
Hey! Thanks for writing this up, the text app uses the file extension to inform the syntax highlighting, so if you renamed your file from "html website.txt" to "html website.html" and tried to open it the app should be able to automatically apply the HTML syntax highlighting. 

Hope this helps! Feel free to reopen the bug if that doesn't do it.
