### ISSUE TITLE
TEXT APP

### ISSUE THREAD

**Issue by markgluth** [GoogleChromeLabs/text-app#516]
I am a new Chrome OS user. I rely on the app Text for writing.    I like that it works off line, saves to my machine, and syncs with drive well.  I  just read that Google is stopping support for Chrome apps in the next  year+.  Is Text one of the apps that will not be supported? I dont really understand what constitutes an "app" in this context.

**Comment by zainafzal08** [comment]
Heya! Thanks for hitting us up, there are no plans for the text app to be removed from chromeos at the moment, when chrome apps lose support we will make sure the text app is still available and functional :)
