### ISSUE TITLE
How close button works?

### ISSUE THREAD

**Issue by ABINASH-KUMAR-ctrl** [GoogleChromeLabs/text-app#532]
I am currently working on a chrome app and i want when I click on button my chrome app closes please tell which api you used for closing the text app.

Please says 
I know that this is not the right place to ask this...
Please

**Comment by zainafzal08** [comment]
Assuming you created your window from a background page (see https://developer.chrome.com/docs/extensions/reference/app_window/ for the chrome.apps.window API) you can just call .close on the window reference.

Note that chrome apps are deprecated so you might wanna instead develop a PWA (see https://developer.chrome.com/docs/apps/migration/ for options on how to migrate a chrome app).
