### ISSUE TITLE
Opening Other Windows Over Text App

### ISSUE THREAD

**Issue by MeMyName** [GoogleChromeLabs/text-app#533]
If I have the text app open and I want to switch to another window, if I go into the overview and select something else it does not open, the text app just shows up again. This also happens when I click on a different app on the shelf, it will not open over the text app. If I want to switch windows, I must click the minimize button in the top right or click the text app icon on the shelf first.

**Comment by RedwolfPrograms** [comment]
If you are on a Windows, Mac, or Linux device, you may have accidentally made it always show on top. Right click the bar on top and there should be an option to undo it.

**Comment by zainafzal08** [comment]
There is also a "always show on top" setting in the app settings which might be toggled on.

**Comment by MeMyName** [comment]
I am using a chromebook and I'm pretty sure that is not a setting.
