### ISSUE TITLE
Google is discontinuing apps for google chrome

### ISSUE THREAD

**Issue by ethanaobrien** [GoogleChromeLabs/text-app#544]
Google Chrome is discontinuing apps for google chrome for all platforms. What should we do. Would it be easy to migrate this to an extension?

https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html

**Comment by zainafzal08** [comment]
The text app team is aware of the migration and is working on a suitable solution. Rest assured the app will be available in some form after the deprecation :)
