### ISSUE TITLE
Undo is limited in 0.8

### ISSUE THREAD

**Issue by 0ct00** [GoogleChromeLabs/text-app#599]
@ZufengW 

In version 0.8 there's a limit to how many times you can undo.

To test do the following:

1. Open a new file
2. Press and hold `ENTER` until you have 200 lines
3. Press and hold `CTRL`+`Z`
4. Undo stops working at line 96

This wasn't the case in previous versions.

**Comment by tim-loh** [comment]
Seems like the default undo level went from 200 to 100, and key repeats on enter no longer get grouped.

https://codemirror.net/5/doc/manual.html#:~:text=undoDepth
https://codemirror.net/docs/ref/#commands.history^config.minDepth
