### ISSUE TITLE
Large Default Font Size

### ISSUE THREAD

**Issue by bffive** [GoogleChromeLabs/text-app#605]
Thanks so much for this app! I've probably been using it for 10 years between the few districts I've worked in for students with Word Processing testing accommodations who aren't allowed spell check. Come test time last spring, every user had the font size default to 28 and I can't seem to get it to stop doing that. I tried power washing the Chromebooks in case there was a weird setting left over, but it continues to happen. Do we think there's a solution to this? I know ctrl + - reduces the font, but the testing coordinator has a job just getting the devices set up to begin with; I think that suggestion would send her over the edge. Worst case scenario, that's what I'll do, but wanted to reach out in case there was another solution! Thanks!

**Comment by tim-loh** [comment]
Font size should be synced to the user account, so if you're using the same account on every device then it might have gotten synced to 28. I had a quick look and it doesn't seem like we're made changes around those parts in a (very) long time, so I'm not sure what else might be causing it.

**Comment by bffive** [comment]
I never thanked you for this. It never occurred to that it'd be a setting that would be tied to the account, but sure enough it was! Thanks for the help!
