### ISSUE TITLE
Detect indentation based on style for the file

### ISSUE THREAD

**Issue by joshwoodward** [GoogleChromeLabs/text-app#66]
It seems to assume 4 spaces = 1 tab, but the standard google indent is 2 spaces--so if I'm at a 2nd level indent (4 spaces) and hit backspace, it puts the cursor all the way left instead of 2 spaces from the edge.  Would be nice if it were smarter about detecting the indentation style for the file.

**Comment by BugsNash** [comment]
This seems to be fixed by the settings options for tab size and tab to spaces.
